version: "3.8"

services:
  hicdex:
    build: .
    depends_on:
      - powa-repository
    volumes:
      - ./src/hicdex/dipdup.yml:/home/dipdup/dipdup.yml
      - ./src/hicdex/dipdup-docker.yml:/home/dipdup/dipdup-docker.yml
      - ./hicdex-metadata:/home/dipdup/metadata
    command: ["-c", "dipdup.yml", "-c", "dipdup-docker.yml", "run"]
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - ADMIN_SECRET=${ADMIN_SECRET:-changeme}

  db:
    image: postgres:13
    ports:
      - 6423:5432
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v1.3.3
    expose:
      - 8080
    depends_on:
      - powa-repository
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dipdup:${POSTGRES_PASSWORD:-changeme}@db:5432/dipdup
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user

  caddy:
    image: caddy:2.4.0-alpine
    depends_on:
      - "hasura"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hicdex-graphiql:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy_data:/data
      - /opt/caddy_config:/config

